name: CI/CD Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- JOB 1: BUILD FRONTEND (Vite + Nginx) ---
  build-frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push FE
        uses: docker/build-push-action@v5
        with:
          context: ./front-end
          file: ./front-end/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mernstack-ecommerce-fe:latest
          # Thêm Cache để build nhanh hơn
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # --- JOB 2: BUILD BACKEND (Node.js/Babel) ---
  build-backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push BE
        uses: docker/build-push-action@v5
        with:
          context: ./nodejs-api
          file: ./nodejs-api/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mernstack-ecommerce-be:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max